//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class beforeremovalnotice
    {
        public long aid { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string SubscriberName { get; set; }
        public string SubscriberAddress { get; set; }
        public string AgreementNo { get; set; }
        public string DeputyRegistrarChits { get; set; }
        public string ChitNo { get; set; }
        public Nullable<int> ArrearsInstalmentFrom { get; set; }
        public Nullable<int> ArrearsInstalmentTo { get; set; }
        public Nullable<int> InterestPAFrom { get; set; }
        public Nullable<int> InterestPATo { get; set; }
        public Nullable<decimal> InstalmentRs { get; set; }
        public Nullable<decimal> InterestRs { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string branchid { get; set; }
        public string Head_id { get; set; }
        public Nullable<System.DateTime> AgreementDate { get; set; }
        public Nullable<int> AgreementYear { get; set; }
    }
}
