//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class dailyactivity
    {
        public long ano { get; set; }
        public System.DateTime date { get; set; }
        public long empid { get; set; }
        public string vehiclenumber { get; set; }
        public string repairdetails { get; set; }
        public long branchid { get; set; }
        public System.Guid DualTransactionKey { get; set; }
    }
}
