//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class fd
    {
        public long idFD { get; set; }
        public int ChitNumber { get; set; }
        public System.DateTime Date { get; set; }
        public int BranchID { get; set; }
        public Nullable<System.Guid> DualTransactionKey { get; set; }
    }
}
