//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class filingfee
    {
        public long idFilingFees { get; set; }
        public System.Guid DualTransactionKey { get; set; }
        public int ChitNumber { get; set; }
        public int GroupNumber { get; set; }
        public string MemberName { get; set; }
        public System.DateTime ChoosenDate { get; set; }
        public Nullable<System.DateTime> DrawDate { get; set; }
        public string DrawNumber { get; set; }
        public decimal Amount { get; set; }
        public string Details { get; set; }
        public int HeadID { get; set; }
        public int FilingID { get; set; }
        public int MemberID { get; set; }
        public int BranchID { get; set; }
    }
}
