//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class moneycollector
    {
        public long BranchID { get; set; }
        public long moneycollid { get; set; }
        public string moneycollname { get; set; }
        public string moneycolladdress { get; set; }
        public string moneycollphno { get; set; }
        public long employeeid { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ISActive { get; set; }
        public Nullable<bool> Flag { get; set; }
    }
}
