//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class reauctionparticular
    {
        public Nullable<long> RefNo { get; set; }
        public Nullable<System.DateTime> OldAuctionDate { get; set; }
        public Nullable<long> OldPrizedToken { get; set; }
        public Nullable<long> OldPrizedMember { get; set; }
        public long GroupID { get; set; }
        public long BranchId { get; set; }
        public long id { get; set; }
    }
}
