//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class rejectedmember
    {
        public int slno { get; set; }
        public string GrpMemberID { get; set; }
        public string GroupID { get; set; }
        public string MemberID { get; set; }
        public Nullable<System.DateTime> RejectedDate { get; set; }
    }
}
