//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class removal_approval
    {
        public long SNo { get; set; }
        public long BranchId { get; set; }
        public long ChitNO { get; set; }
        public long OldMemberID { get; set; }
        public long GroupMemberID { get; set; }
        public long NewMemberID { get; set; }
        public Nullable<System.DateTime> DateOfRemoval { get; set; }
        public string ReasonForRemoval { get; set; }
        public Nullable<System.DateTime> C1stNoticeDate { get; set; }
        public Nullable<System.DateTime> C2ndNoticeDate { get; set; }
        public long CurrentDrawNumber { get; set; }
        public string EstimatedDrawNumber { get; set; }
        public string EstimatedSurityDetails { get; set; }
        public Nullable<System.DateTime> SubstitutedDate { get; set; }
        public Nullable<System.DateTime> RejectionDate { get; set; }
        public long M_ID { get; set; }
        public long B_ID { get; set; }
        public string RejectionReason { get; set; }
        public bool card { get; set; }
        public long Flag { get; set; }
        public string profession { get; set; }
        public string suggesionifany { get; set; }
        public Nullable<long> istransfered { get; set; }
        public Nullable<System.DateTime> intimationdate { get; set; }
        public Nullable<System.DateTime> substitutedate { get; set; }
    }
}
