//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class right
    {
        public long aid { get; set; }
        public System.Guid DualTransactionKey { get; set; }
        public long roleid { get; set; }
        public long memberid { get; set; }
    }
}
