//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class substitutedmaster
    {
        public int SNo { get; set; }
        public long BranchId { get; set; }
        public Nullable<long> ChitNO { get; set; }
        public Nullable<long> OldMemberID { get; set; }
        public long GroupMemberID { get; set; }
        public Nullable<long> NewMemberID { get; set; }
        public Nullable<System.DateTime> DateOfRemoval { get; set; }
        public string ReasonForRemoval { get; set; }
        public Nullable<System.DateTime> C1stNoticeDate { get; set; }
        public Nullable<System.DateTime> C2ndNoticeDate { get; set; }
        public Nullable<System.DateTime> SubstitutedDate { get; set; }
        public string IFlag { get; set; }
        public Nullable<long> CurrentDrawNumber { get; set; }
        public Nullable<long> EstimatedDrawNumber { get; set; }
        public string EstimatedSurityDetails { get; set; }
        public string MoneyCollectorID { get; set; }
        public string DescriptionFromSuggestor { get; set; }
    }
}
