//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class transcourt
    {
        public long ano { get; set; }
        public System.Guid DualTransactionKey { get; set; }
        public long TransactionKey { get; set; }
        public long HeadID { get; set; }
        public string CC { get; set; }
        public string Number { get; set; }
        public System.DateTime ChoosenDate { get; set; }
        public string Narration { get; set; }
        public long BranchID { get; set; }
        public string VoucherType { get; set; }
        public bool Flag { get; set; }
        public bool istransfered { get; set; }
        public int ReHeadId { get; set; }
        public System.DateTime ApplyedOn { get; set; }
        public int AdminSanctionNo { get; set; }
    }
}
