//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class transprofitandloss
    {
        public long ano { get; set; }
        public long BranchID { get; set; }
        public System.Guid DualTransactionKey { get; set; }
        public long TransactionKey { get; set; }
        public long HeadID { get; set; }
        public string Narration { get; set; }
        public string aosanction { get; set; }
        public Nullable<long> OppositeHeadId { get; set; }
        public Nullable<long> ChequeNo { get; set; }
        public System.DateTime ApplyedOn { get; set; }
        public Nullable<long> AcceptNumber { get; set; }
        public long Flag { get; set; }
    }
}
