//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class voucherdeleted
    {
        public long TransactionKey { get; set; }
        public System.Guid DualTransactionKey { get; set; }
        public long BranchID { get; set; }
        public System.DateTime CurrDate { get; set; }
        public int Voucher_No { get; set; }
        public string Voucher_Type { get; set; }
        public long Head_Id { get; set; }
        public System.DateTime ChoosenDate { get; set; }
        public string Narration { get; set; }
        public decimal Amount { get; set; }
        public string Series { get; set; }
        public string ReceievedBy { get; set; }
        public bool Trans_Type { get; set; }
        public int T_Day { get; set; }
        public int T_Month { get; set; }
        public int T_Year { get; set; }
        public Nullable<int> MemberID { get; set; }
        public bool Trans_Medium { get; set; }
        public int RootID { get; set; }
        public Nullable<int> ChitGroupId { get; set; }
        public int Other_Trans_Type { get; set; }
        public int IsDeleted { get; set; }
        public int IsAccepted { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ISActive { get; set; }
        public string AppReceiptno { get; set; }
        public Nullable<System.DateTime> removedDt { get; set; }
        public string sysip { get; set; }
    }
}
