//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SVCF_DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class branchdetail
    {
        public long B_Code { get; set; }
        public string B_Name { get; set; }
        public string B_Head { get; set; }
        public string B_Address { get; set; }
        public string B_PhoneNo { get; set; }
        public string B_EMail { get; set; }
        public Nullable<System.DateTime> B_DOC { get; set; }
        public long Head_Id { get; set; }
        public long aid { get; set; }
        public string Place { get; set; }
    }
}
